# Copyright (c) 2020 - 2026 Open Risk (https://www.openriskmanagement.com)
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.


"""
 head -1 policy/fixtures/policy_data/Oxford_Policies_Report_Latest.csv

CountryName,CountryCode,RegionName,RegionCode,Jurisdiction,Date,C1_School closing,C1_Flag,C2_Workplace closing,C2_Flag,C3_Cancel public events,C3_Flag,C4_Restrictions on gatherings,C4_Flag,C5_Close public transport,C5_Flag,C6_Stay at home requirements,C6_Flag,C7_Restrictions on internal movement,C7_Flag,C8_International travel controls,E1_Income support,E1_Flag,E2_Debt/contract relief,E3_Fiscal measures,E4_International support,H1_Public information campaigns,H1_Flag,H2_Testing policy,H3_Contact tracing,H4_Emergency investment in healthcare,H5_Investment in vaccines,

H6_Facial Coverings,

H6_Flag,

H7_Vaccination policy,

H7_Flag,

M1_Wildcard,

ConfirmedCases,ConfirmedDeaths,StringencyIndex,StringencyIndexForDisplay,StringencyLegacyIndex,StringencyLegacyIndexForDisplay,GovernmentResponseIndex,GovernmentResponseIndexForDisplay,ContainmentHealthIndex,ContainmentHealthIndexForDisplay,EconomicSupportIndex,EconomicSupportIndexForDisplay


"""

# The covid policy field names as they are in the CSV header
field_names_old = ['C1_School closing',
                   'C1_Flag',
                   'C2_Workplace closing',
                   'C2_Flag',
                   'C3_Cancel public events',
                   'C3_Flag',
                   'C4_Restrictions on gatherings',
                   'C4_Flag',
                   'C5_Close public transport',
                   'C5_Flag',
                   'C6_Stay at home requirements',
                   'C6_Flag',
                   'C7_Restrictions on internal movement',
                   'C7_Flag',
                   'C8_International travel controls',
                   'E1_Income support', 'E1_Flag',
                   'E2_Debt/contract relief',
                   'E3_Fiscal measures',
                   'E4_International support',
                   'H1_Public information campaigns',
                   'H1_Flag',
                   'H2_Testing policy',
                   'H3_Contact tracing',
                   'H4_Emergency investment in healthcare',
                   'H5_Investment in vaccines',
                   'H6_Facial Coverings',
                   'H6_Flag',
                   'H7_Vaccination policy',
                   'H7_Flag',
                   'M1_Wildcard',
                   'ConfirmedCases',
                   'ConfirmedDeaths',
                   'StringencyIndex',
                   'StringencyIndexForDisplay',
                   'StringencyLegacyIndex',
                   'StringencyLegacyIndexForDisplay',
                   'GovernmentResponseIndex',
                   'GovernmentResponseIndexForDisplay',
                   'ContainmentHealthIndex',
                   'ContainmentHealthIndexForDisplay',
                   'EconomicSupportIndex',
                   'EconomicSupportIndexForDisplay'
                   ]

field_names = ['C1M_School closing',
               'C1M_Flag',
               'C2M_Workplace closing',
               'C2M_Flag',
               'C3M_Cancel public events',
               'C3M_Flag',
               'C4M_Restrictions on gatherings',
               'C4M_Flag',
               'C5M_Close public transport',
               'C5M_Flag',
               'C6M_Stay at home requirements',
               'C6M_Flag',
               'C7M_Restrictions on internal movement',
               'C7M_Flag',
               'C8EV_International travel controls',
               'E1_Income support',
               'E1_Flag',
               'E2_Debt/contract relief',
               'E3_Fiscal measures',
               'E4_International support',
               'H1_Public information campaigns',
               'H1_Flag',
               'H2_Testing policy',
               'H3_Contact tracing',
               'H4_Emergency investment in healthcare',
               'H5_Investment in vaccines',
               'H6M_Facial Coverings',
               'H6M_Flag',
               'H7_Vaccination policy',
               'H7_Flag',
               'H8M_Protection of elderly people',
               'H8M_Flag',
               'V1_Vaccine Prioritisation (summary)',
               'V2A_Vaccine Availability (summary)',
               'V2B_Vaccine age eligibility/availability age floor (general population summary)',
               'V2C_Vaccine age eligibility/availability age floor (at risk summary)',
               'V2D_Medically/ clinically vulnerable (Non-elderly)',
               'V2E_Education',
               'V2F_Frontline workers  (non healthcare)',
               'V2G_Frontline workers  (healthcare)',
               'V3_Vaccine Financial Support (summary)',
               'V4_Mandatory Vaccination (summary)',
               'ConfirmedCases',
               'ConfirmedDeaths',
               'MajorityVaccinated',
               'PopulationVaccinated',
               'StringencyIndex_Average',
               'GovernmentResponseIndex_Average',
               'ContainmentHealthIndex_Average',
               'EconomicSupportIndex'
               ]

# Field codes as constructed / simplified from the CSV headers
field_codes_old = ['C1',
               'C1F',
               'C2',
               'C2F',
               'C3',
               'C3F',
               'C4',
               'C4F',
               'C5',
               'C5F',
               'C6',
               'C6F',
               'C7',
               'C7F',
               'C8',
               'E1',
               'E1F',
               'E2',
               'E3',
               'E4',
               'H1',
               'H1F',
               'H2',
               'H3',
               'H4',
               'H5',
               'H6',
               'H6F',
               'H7',
               'H7F',
               'M1',
               'AUX1',
               'AUX2',
               'I1',
               'I1D',
               'I2',
               'I2D',
               'I3',
               'I3D',
               'I4',
               'I4D',
               'I5',
               'I5D'
               ]

field_codes = ['C1',
               'C1F',
               'C2',
               'C2F',
               'C3',
               'C3F',
               'C4',
               'C4F',
               'C5',
               'C5F',
               'C6',
               'C6F',
               'C7',
               'C7F',
               'C8',
               'E1',
               'E1F',
               'E2',
               'E3',
               'E4',
               'H1',
               'H1F',
               'H2',
               'H3',
               'H4',
               'H5',
               'H6',
               'H6F',
               'H7',
               'H7F',
               'H8',
               'H8F',
               'V1',
               'V2A',
               'V2B',
               'V2C',
               'V2D',
               'V2E',
               'V2F',
               'V2G',
               'V3',
               'V4',
               'I1',
               'I2',
               'I3',
               'I4',
               'I5',
               'I6',
               'I7',
               'I8'
               ]

# field description (from CSV headers)
field_description = ['School closing',
                     'School closing Flag',
                     'Workplace closing',
                     'Workplace closing Flag',
                     'Cancel public events',
                     'Cancel public events Flag',
                     'Restrictions on gatherings',
                     'Restrictions on gatherings Flag',
                     'Close public transport',
                     'Close public transport Flag',
                     'Stay at home requirements',
                     'Stay at home requirements Flag',
                     'Restrictions on internal movement',
                     'Restrictions on internal movement Flag',
                     'International travel controls',
                     'Income support',
                     'Income support Flag',
                     'Debt/contract relief',
                     'Fiscal measures',
                     'International support',
                     'Public information campaigns',
                     'Public information campaigns Flag',
                     'Testing policy',
                     'Contact tracing',
                     'Emergency investment in healthcare',
                     'Investment in vaccines',
                     'Facial Coverings',
                     'Facial Coverings Flag',
                     'Vaccination Policy',
                     'Vaccination Policy Flag',
                     'Protection of elderly people',
                     'Protection of elderly people Flag',
                     'Vaccine Prioritisation (summary)',
                     'Vaccine Availability (summary)',
                     'Vaccine age eligibility/availability age floor (summary)',
                     'Vaccine age eligibility/availability age floor (at risk summary)',
                     'Medically / clinically vulnerable (Non-elderly)',
                     'Education',
                     'Frontline workers (non healthcare)',
                     'Frontline workers (healthcare)',
                     'Vaccine Financial Support (summary)',
                     'Mandatory Vaccination (summary)',
                     'Confirmed Cases',
                     'Confirmed Deaths',
                     'Majority Vaccinated',
                     'Population Vaccinated',
                     'Stringency Index Average',
                     'Government Response Index Average',
                     'Containment Health Index Average',
                     'Economic Support Index Average'
                     ]

field_description_long = field_description

# from codebook
field_description_long_old = ['Record closings of schools and universities',
                          'School closing Flag',
                          'Record closings of workplaces',
                          'Workplace closing Flag',
                          'Record cancelling public events',
                          'Cancel public events Flag',
                          'Record limits on private gatherings',
                          'Restrictions on gatherings Flag',
                          'Record closing of public transport',
                          'Close public transport Flag',
                          'Record orders to "shelter-in-place" and otherwise confine to the home',
                          'Stay at home requirements Flag',
                          'Record restrictions on internal movement between cities/regions',
                          'Restrictions on internal movement Flag',
                          'Record restrictions on international travel (for foreign travellers, not citizens)',
                          'Record if the government is providing direct cash payments to people who lose their jobs or cannot work. Note: only includes payments to firms if explicitly linked to payroll/salaries',
                          'Income support Flag',
                          'Record if the government is freezing financial obligations for households (eg stopping loan repayments, preventing services like water from stopping, or banning evictions)',
                          'Announced economic stimulus spending. Note: only records amount additional to previously announced spending',
                          'Announced offers of Covid-19 related aid spending to other countries. Note: only record amount additional to previously announced spending',
                          'Record presence of public info campaigns',
                          'Public information campaigns Flag',
                          'Record government policy on who has access to testing. Note: this records policies about testing for current infection (PCR tests) not testing for immunity (antibody test)',
                          'Record government policy on contact tracing after a positive diagnosis. Note: we are looking for policies that would identify all people potentially exposed to Covid-19; voluntary bluetooth apps are unlikely to achieve this',
                          'Announced short term spending on healthcare system, eg hospitals, masks, etc. Note: only records amount additional to previously announced spending',
                          'Announced public spending on Covid-19 vaccine development. Note: only record amount additional to previously announced spending',
                          'Record policies on the use of facial coverings outside the home',
                          'Facial Coverings Flag',
                          'Record policies for vaccine delivery for different groups',
                          'Vaccine Policies Flag',
                          'Wildcard',
                          'Confirmed Cases',
                          'Confirmed Deaths',
                          'Stringency Index',
                          'Stringency Index For Display',
                          'Stringency Legacy Index',
                          'Stringency Legacy Index For Display',
                          'Government Response Index',
                          'Government Response Index For Display',
                          'Containment Health Index',
                          'Containment Health Index For Display',
                          'Economic Support Index',
                          'Economic Support Index For Display'
                          ]

# code list from codebook.md
# https://github.com/OxCGRT/covid-policy-dataset/blob/main/documentation_and_codebook.md

field_code_list = {'C1': {'0': 'no measures',
                          '1': 'recommend closing',
                          '2': 'require closing (only some levels or categories, eg just high school, or just public schools)',
                          '3': 'require closing all levels'},
                   'C1F': {'0': 'no measures',
                           '1': 'general'},
                   'C2': {'0': 'no measures',
                          '1': 'recommend closing (or recommend work from home)',
                          '2': 'require closing (or work from home) for some sectors or categories of workers',
                          '3': 'require closing (or work from home) for all-but-essential workplaces (eg grocery stores, doctors)'},
                   'C2F': {'0': 'targeted',
                           '1': 'general'},
                   'C3': {'0': 'no measures',
                          '1': 'recommend cancelling',
                          '2': 'require cancelling'},
                   'C3F': {'0': 'targeted',
                           '1': 'general'},
                   'C4': {'0': 'no restrictions',
                          '1': 'restrictions on very large gatherings (the limit is above 1000 people)',
                          '2': 'restrictions on gatherings between 101-1000 people',
                          '3': 'restrictions on gatherings between 11-100 people',
                          '4': 'restrictions on gatherings of 10 people or less'},
                   'C4F': {'0': 'targeted',
                           '1': 'general'},
                   'C5': {'0': 'no measures',
                          '1': 'recommend closing (or significantly reduce volume/route/means of transport available)',
                          '2': 'require closing (or prohibit most citizens from using it)'},
                   'C5F': {'0': 'targeted',
                           '1': 'general'},
                   'C6': {'0': 'no measures',
                          '1': 'recommend not leaving house',
                          '2': 'require not leaving house with exceptions for daily exercise, grocery shopping, and essential trips',
                          '3': 'require not leaving house with minimal exceptions (eg allowed to leave once a week, or only one person can leave at a time, etc)'},
                   'C6F': {'0': 'targeted',
                           '1': 'general'},
                   'C7': {'0': 'no measures',
                          '1': 'recommend not to travel between regions/cities',
                          '2': 'internal movement restrictions in place'},
                   'C7F': {'0': 'targeted',
                           '1': 'general'},
                   'C8': {'0': 'no restrictions',
                          '1': 'screening arrivals',
                          '2': 'quarantine arrivals from some or all regions',
                          '3': 'ban arrivals from some regions',
                          '4': 'ban on all regions or total border closure'},
                   'E1': {'0': 'no income support',
                          '1': 'government is replacing less than 50% of lost salary (or if a flat sum, it is less than 50% median salary)',
                          '2': 'government is replacing 50% or more of lost salary (or if a flat sum, it is greater than 50% median salary)'},
                   'E1F': {'0': 'formal sector workers only',
                           '1': 'transfers to informal sector workers too'},
                   'E2': {'0': 'no',
                          '1': 'Narrow relief, specific to one kind of contract',
                          '2': 'broad debt/contract relief'},
                   'E3': {'0': 'numerical variable (USD). Record monetary value in USD of fiscal stimuli, includes any spending or tax cuts NOT included in E4, H4 or H5'},
                   'E4': {'0': 'numerical variable (USD)'},
                   'H1': {'0': 'No COVID-19 public information campaign',
                          '1': 'public officials urging caution about COVID-19',
                          '2': 'coordinated public information campaign (e.g. across traditional and social media)'},
                   'H1F': {'0': 'targeted',
                           '1': 'general'},
                   'H2': {'0': 'no testing policy',
                          '1': 'only those who both (a) have symptoms AND (b) meet specific criteria (eg key workers, admitted to hospital, came into contact with a known case, returned from overseas)',
                          '2': 'testing of anyone showing Covid-19 symptoms',
                          '3': 'open public testing (eg "drive through" testing available to asymptomatic people)'},
                   'H3': {'0': 'no contact tracing',
                          '1': 'limited contact tracing; not done for all cases',
                          '2': 'comprehensive contact tracing; done for all identified cases'},
                   'H4': {'0': 'numerical variable, Record monetary value in USD'},
                   'H5': {'0': 'numerical variable, Record monetary value in USD'},
                   'H6': {'0': 'No policy', '1': 'Recommended',
                          '2': 'Required in some specified shared/public spaces outside the home with other people present, or some situations when social distancing not possible',
                          '3': 'Required in all shared/public spaces outside the home with other people present or all situations when social distancing not possible',
                          '4': 'Required outside the home at all times regardless of location or presence of other people'},
                   'H6F': {'0': 'targeted',
                           '1': 'general'},
                   'H7': {'0': 'No availability',
                          '1': 'Availability for ONE of following: key workers/ clinically vulnerable groups / elderly groups',
                          '2':
                              'Availability for TWO of following: key workers/ clinically vulnerable groups / elderly groups',
                          '3': 'Availability for ALL of following: key workers/ clinically vulnerable groups / elderly groups',
                          '4': 'Availability for all three plus partial additional availability (select broad groups/ages)',
                          '5': 'Universal availability'},
                   'H7F': {'0': 'At cost to individual (or funded by NGO, insurance, or partially government funded)',
                           '1': 'No or minimal cost to individual (government funded or subsidised)'},
                   'H8': {'0': 'No measures',
                          '1': 'Recommended isolation, hygiene, and visitor restriction measures in LTCFs and/or elderly people to stay at home',
                          '2':
                              'Narrow restrictions for isolation, hygiene in LTCFs, some limitations on external visitors and/or restrictions protecting elderly people at home',
                          '3': 'Extensive restrictions for isolation and hygiene in LTCFs, all non-essential external visitors prohibited, and/or all elderly people required to stay at home and not leave the home with minimal exceptions, and receive no external visitors'},
                   'H8F': {'0': 'targeted',
                           '1': 'general'},
                   'V1': {'0': 'numerical variable'},
                   'V2A': {'0': 'numerical variable'},
                   'V2B': {'0': 'numerical variable'},
                   'V2C': {'0': 'numerical variable'},
                   'V2D': {'0': 'numerical variable'},
                   'V2E': {'0': 'numerical variable'},
                   'V2F': {'0': 'numerical variable'},
                   'V2G': {'0': 'numerical variable'},
                   'V3': {'0': 'numerical variable'},
                   'V4': {'0': 'numerical variable'},
                   'I1': {'0': 'numerical variable'},
                   'I2': {'0': 'numerical variable'},
                   'I3': {'0': 'numerical variable'},
                   'I4': {'0': 'numerical variable'},
                   'I5': {'0': 'numerical variable'},
                   'I6': {'0': 'numerical variable'},
                   'I7': {'0': 'numerical variable'},
                   'I8': {'0': 'numerical variable'}
                   }

field_type = ['ordinal',
              'binary',
              'ordinal',
              'binary',
              'ordinal',
              'binary',
              'ordinal',
              'binary',
              'ordinal',
              'binary',
              'ordinal',
              'binary',
              'ordinal',
              'binary',
              'ordinal',
              'ordinal',
              'binary',
              'ordinal',
              'numerical',
              'numerical',
              'ordinal',
              'binary',
              'ordinal',
              'ordinal',
              'numerical',
              'numerical',
              'text',
              'ordinal',
              'ordinal',
              'ordinal',
              'ordinal',
              'numerical',
              'numerical',
              'numerical',
              'text',
              'text',
              'numerical',
              'numerical',
              'numerical',
              'numerical',
              'numerical',
              'numerical',
              'numerical',
              'numerical',
              'text',
              'numerical',
              'numerical',
              'numerical',
              'numerical',
              'numerical'
              ]
