# Copyright (c) 2020 - 2025 Open Risk (https://www.openriskmanagement.com)
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

NACE_DICT = {'A1.1': 'Growing of non-perennial crops',
             'A1.2': 'Growing of perennial crops',
             'A1.3': 'Plant propagation',
             'A1.4': 'Animal production',
             'A1.5': 'Mixed farming',
             'A1.6': 'Support activities to agriculture and post-harvest crop '
                     'activities',
             'A1.7': 'Hunting, trapping and related service activities',
             'A2.1': 'Silviculture and other forestry activities',
             'A2.2': 'Logging',
             'A2.3': 'Gathering of wild growing non-wood products',
             'A2.4': 'Support services to forestry',
             'A3.1': 'Fishing',
             'A3.2': 'Aquaculture',
             'B5.1': 'Mining of hard coal',
             'B5.2': 'Mining of lignite',
             'B6.1': 'Extraction of crude petroleum',
             'B6.2': 'Extraction of natural gas',
             'B7.1': 'Mining of iron ores',
             'B7.2': 'Mining of non-ferrous metal ores',
             'B8.1': 'Quarrying of stone, sand and clay',
             'B8.9': 'Mining and quarrying n.e.c.',
             'B9.1': 'Support activities for petroleum and natural gas extraction',
             'B9.9': 'Support activities for other mining and quarrying',
             'C10.1': 'Processing and preserving of meat and production of meat '
                      'products',
             'C10.2': 'Processing and preserving of fish, crustaceans and molluscs',
             'C10.3': 'Processing and preserving of fruit and vegetables',
             'C10.4': 'Manufacture of vegetable and animal oils and fats',
             'C10.5': 'Manufacture of dairy products',
             'C10.6': 'Manufacture of grain mill products, starches and starch '
                      'products',
             'C10.7': 'Manufacture of bakery and farinaceous products',
             'C10.8': 'Manufacture of other food products',
             'C10.9': 'Manufacture of prepared animal feeds',
             'C11.0': 'Manufacture of beverages',
             'C12.0': 'Manufacture of tobacco products',
             'C13.1': 'Preparation and spinning of textile fibres',
             'C13.2': 'Weaving of textiles',
             'C13.3': 'Finishing of textiles',
             'C13.9': 'Manufacture of other textiles',
             'C14.1': 'Manufacture of wearing apparel, except fur apparel',
             'C14.2': 'Manufacture of articles of fur',
             'C14.3': 'Manufacture of knitted and crocheted apparel',
             'C15.1': 'Tanning and dressing of leather; manufacture of luggage, '
                      'handbags, saddlery and harness; dressing and dyeing of fur',
             'C15.2': 'Manufacture of footwear',
             'C16.1': 'Sawmilling and planing of wood',
             'C16.2': 'Manufacture of products of wood, cork, straw and plaiting '
                      'materials',
             'C17.1': 'Manufacture of pulp, paper and paperboard',
             'C17.2': 'Manufacture of articles of paper and paperboard',
             'C18.1': 'Printing and service activities related to printing',
             'C18.2': 'Reproduction of recorded media',
             'C19.1': 'Manufacture of coke oven products',
             'C19.2': 'Manufacture of refined petroleum products',
             'C20.1': 'Manufacture of basic chemicals, fertilisers and nitrogen '
                      'compounds, plastics and synthetic rubber in primary forms',
             'C20.2': 'Manufacture of pesticides and other agrochemical products',
             'C20.3': 'Manufacture of paints, varnishes and similar coatings, '
                      'printing ink and mastics',
             'C20.4': 'Manufacture of soap and detergents, cleaning and polishing '
                      'preparations, perfumes and toilet preparations',
             'C20.5': 'Manufacture of other chemical products',
             'C20.6': 'Manufacture of man-made fibres',
             'C21.1': 'Manufacture of basic pharmaceutical products',
             'C21.2': 'Manufacture of pharmaceutical preparations',
             'C22.1': 'Manufacture of rubber products',
             'C22.2': 'Manufacture of plastics products',
             'C23.1': 'Manufacture of glass and glass products',
             'C23.2': 'Manufacture of refractory products',
             'C23.3': 'Manufacture of clay building materials',
             'C23.4': 'Manufacture of other porcelain and ceramic products',
             'C23.5': 'Manufacture of cement, lime and plaster',
             'C23.6': 'Manufacture of articles of concrete, cement and plaster',
             'C23.7': 'Cutting, shaping and finishing of stone',
             'C23.9': 'Manufacture of abrasive products and non-metallic mineral '
                      'products n.e.c.',
             'C24.1': 'Manufacture of basic iron and steel and of ferro-alloys',
             'C24.2': 'Manufacture of tubes, pipes, hollow profiles and related '
                      'fittings, of steel',
             'C24.3': 'Manufacture of other products of first processing of steel',
             'C24.4': 'Manufacture of basic precious and other non-ferrous metals',
             'C24.5': 'Casting of metals',
             'C25.1': 'Manufacture of structural metal products',
             'C25.2': 'Manufacture of tanks, reservoirs and containers of metal',
             'C25.3': 'Manufacture of steam generators, except central heating hot '
                      'water boilers',
             'C25.4': 'Manufacture of weapons and ammunition',
             'C25.5': 'Forging, pressing, stamping and roll-forming of metal; powder '
                      'metallurgy',
             'C25.6': 'Treatment and coating of metals; machining',
             'C25.7': 'Manufacture of cutlery, tools and general hardware',
             'C25.9': 'Manufacture of other fabricated metal products',
             'C26.1': 'Manufacture of electronic components and boards',
             'C26.2': 'Manufacture of computers and peripheral equipment',
             'C26.3': 'Manufacture of communication equipment',
             'C26.4': 'Manufacture of consumer electronics',
             'C26.5': 'Manufacture of instruments and appliances for measuring, '
                      'testing and navigation; watches and clocks',
             'C26.6': 'Manufacture of irradiation, electromedical and '
                      'electrotherapeutic equipment',
             'C26.7': 'Manufacture of optical instruments and photographic equipment',
             'C26.8': 'Manufacture of magnetic and optical media',
             'C27.1': 'Manufacture of electric motors, generators, transformers and '
                      'electricity distribution and control apparatus',
             'C27.2': 'Manufacture of batteries and accumulators',
             'C27.3': 'Manufacture of wiring and wiring devices',
             'C27.4': 'Manufacture of electric lighting equipment',
             'C27.5': 'Manufacture of domestic appliances',
             'C27.9': 'Manufacture of other electrical equipment',
             'C28.1': 'Manufacture of general-purpose machinery',
             'C28.2': 'Manufacture of other general-purpose machinery',
             'C28.3': 'Manufacture of agricultural and forestry machinery',
             'C28.4': 'Manufacture of metal forming machinery and machine tools',
             'C28.9': 'Manufacture of other special-purpose machinery',
             'C29.1': 'Manufacture of motor vehicles',
             'C29.2': 'Manufacture of bodies (coachwork) for motor vehicles; '
                      'manufacture of trailers and semi-trailers',
             'C29.3': 'Manufacture of parts and accessories for motor vehicles',
             'C30.1': 'Building of ships and boats',
             'C30.2': 'Manufacture of railway locomotives and rolling stock',
             'C30.3': 'Manufacture of air and spacecraft and related machinery',
             'C30.4': 'Manufacture of military fighting vehicles',
             'C30.9': 'Manufacture of transport equipment n.e.c.',
             'C31.0': 'Manufacture of furniture',
             'C32.1': 'Manufacture of jewellery, bijouterie and related articles',
             'C32.2': 'Manufacture of musical instruments',
             'C32.3': 'Manufacture of sports goods',
             'C32.4': 'Manufacture of games and toys',
             'C32.5': 'Manufacture of medical and dental instruments and supplies',
             'C32.9': 'Manufacturing n.e.c.',
             'C33.1': 'Repair of fabricated metal products, machinery and equipment',
             'C33.2': 'Installation of industrial machinery and equipment',
             'D35.1': 'Electric power generation, transmission and distribution',
             'D35.2': 'Manufacture of gas; distribution of gaseous fuels through mains',
             'D35.3': 'Steam and air conditioning supply',
             'E36.0': 'Water collection, treatment and supply',
             'E37.0': 'Sewerage',
             'E38.1': 'Waste collection',
             'E38.2': 'Waste treatment and disposal',
             'E38.3': 'Materials recovery',
             'E39.0': 'Remediation activities and other waste management services',
             'F41.1': 'Development of building projects',
             'F41.2': 'Construction of residential and non-residential buildings',
             'F42.1': 'Construction of roads and railways',
             'F42.2': 'Construction of utility projects',
             'F42.9': 'Construction of other civil engineering projects',
             'F43.1': 'Demolition and site preparation',
             'F43.2': 'Electrical, plumbing and other construction installation '
                      'activities',
             'F43.3': 'Building completion and finishing',
             'F43.9': 'Other specialised construction activities',
             'G45.1': 'Sale of motor vehicles',
             'G45.2': 'Maintenance and repair of motor vehicles',
             'G45.3': 'Sale of motor vehicle parts and accessories',
             'G45.4': 'Sale, maintenance and repair of motorcycles and related parts '
                      'and accessories',
             'G46.1': 'Wholesale on a fee or contract basis',
             'G46.2': 'Wholesale of agricultural raw materials and live animals',
             'G46.3': 'Wholesale of food, beverages and tobacco',
             'G46.4': 'Wholesale of household goods',
             'G46.5': 'Wholesale of information and communication equipment',
             'G46.6': 'Wholesale of other machinery, equipment and supplies',
             'G46.7': 'Other specialised wholesale',
             'G46.9': 'Non-specialised wholesale trade',
             'G47.1': 'Retail sale in non-specialised stores',
             'G47.2': 'Retail sale of food, beverages and tobacco in specialised '
                      'stores',
             'G47.3': 'Retail sale of automotive fuel in specialised stores',
             'G47.4': 'Retail sale of information and communication equipment in '
                      'specialised stores',
             'G47.5': 'Retail sale of other household equipment in specialised stores',
             'G47.6': 'Retail sale of cultural and recreation goods in specialised '
                      'stores',
             'G47.7': 'Retail sale of other goods in specialised stores',
             'G47.8': 'Retail sale via stalls and markets',
             'G47.9': 'Retail trade not in stores, stalls or markets',
             'H49.1': 'Passenger rail transport, interurban',
             'H49.2': 'Freight rail transport',
             'H49.3': 'Other passenger land transport',
             'H49.4': 'Freight transport by road and removal services',
             'H49.5': 'Transport via pipeline',
             'H50.1': 'Sea and coastal passenger water transport',
             'H50.2': 'Sea and coastal freight water transport',
             'H50.3': 'Inland passenger water transport',
             'H50.4': 'Inland freight water transport',
             'H51.1': 'Passenger air transport',
             'H51.2': 'Freight air transport and space transport',
             'H52.1': 'Warehousing and storage',
             'H52.2': 'Support activities for transportation',
             'H53.1': 'Postal activities under universal service obligation',
             'H53.2': 'Other postal and courier activities',
             'I55.1': 'Hotels and similar accommodation',
             'I55.2': 'Holiday and other short-stay accommodation',
             'I55.3': 'Camping grounds, recreational vehicle parks and trailer parks',
             'I55.9': 'Other accommodation',
             'I56.1': 'Restaurants and mobile food service activities',
             'I56.2': 'Event catering and other food service activities',
             'I56.3': 'Beverage serving activities',
             'J58.1': 'Publishing of books, periodicals and other publishing '
                      'activities',
             'J58.2': 'Software publishing',
             'J59.1': 'Motion picture, video and television programme activities',
             'J59.2': 'Sound recording and music publishing activities',
             'J60.1': 'Radio broadcasting',
             'J60.2': 'Television programming and broadcasting activities',
             'J61.1': 'Wired telecommunications activities',
             'J61.2': 'Wireless telecommunications activities',
             'J61.3': 'Satellite telecommunications activities',
             'J61.9': 'Other telecommunications activities',
             'J62.0': 'Computer programming, consultancy and related activities',
             'J63.1': 'Data processing, hosting and related activities; web portals',
             'J63.9': 'Other information service activities',
             'K64.1': 'Monetary intermediation',
             'K64.2': 'Activities of holding companies',
             'K64.3': 'Trusts, funds and similar financial entities',
             'K64.9': 'Other financial service activities, except insurance and '
                      'pension funding',
             'K65.1': 'Insurance',
             'K65.2': 'Reinsurance',
             'K65.3': 'Pension funding',
             'K66.1': 'Activities auxiliary to financial services, except insurance '
                      'and pension funding',
             'K66.2': 'Activities auxiliary to insurance and pension funding',
             'K66.3': 'Fund management activities',
             'L68.1': 'Buying and selling of own real estate',
             'L68.2': 'Renting and operating of own or leased real estate',
             'L68.3': 'Real estate activities on a fee or contract basis',
             'M69.1': 'Legal activities',
             'M69.2': 'Accounting, bookkeeping and auditing activities; tax '
                      'consultancy',
             'M70.1': 'Activities of head offices',
             'M70.2': 'Management consultancy activities',
             'M71.1': 'Architectural and engineering activities and related technical '
                      'consultancy',
             'M71.2': 'Technical testing and analysis',
             'M72.1': 'Research and experimental development on natural sciences and '
                      'engineering',
             'M72.2': 'Research and experimental development on social sciences and '
                      'humanities',
             'M73.1': 'Advertising',
             'M73.2': 'Market research and public opinion polling',
             'M74.1': 'Specialised design activities',
             'M74.2': 'Photographic activities',
             'M74.3': 'Translation and interpretation activities',
             'M74.9': 'Other professional, scientific and technical activities n.e.c.',
             'M75.0': 'Veterinary activities',
             'N77.1': 'Renting and leasing of motor vehicles',
             'N77.2': 'Renting and leasing of personal and household goods',
             'N77.3': 'Renting and leasing of other machinery, equipment and tangible '
                      'goods',
             'N77.4': 'Leasing of intellectual property and similar products, except '
                      'copyrighted works',
             'N78.1': 'Activities of employment placement agencies',
             'N78.2': 'Temporary employment agency activities',
             'N78.3': 'Other human resources provision',
             'N79.1': 'Travel agency and tour operator activities',
             'N79.9': 'Other reservation service and related activities',
             'N80.1': 'Private security activities',
             'N80.2': 'Security systems service activities',
             'N80.3': 'Investigation activities',
             'N81.1': 'Combined facilities support activities',
             'N81.2': 'Cleaning activities',
             'N81.3': 'Landscape service activities',
             'N82.1': 'Office administrative and support activities',
             'N82.2': 'Activities of call centres',
             'N82.3': 'Organisation of conventions and trade shows',
             'N82.9': 'Business support service activities n.e.c.',
             'O84.1': 'Administration of the State and the economic and social policy '
                      'of the community',
             'O84.2': 'Provision of services to the community as a whole',
             'O84.3': 'Compulsory social security activities',
             'P85.1': 'Pre-primary education',
             'P85.2': 'Primary education',
             'P85.3': 'Secondary education',
             'P85.4': 'Higher education',
             'P85.5': 'Other education',
             'P85.6': 'Educational support activities',
             'Q86.1': 'Hospital activities',
             'Q86.2': 'Medical and dental practice activities',
             'Q86.9': 'Other human health activities',
             'Q87.1': 'Residential nursing care activities',
             'Q87.2': 'Residential care activities for mental retardation, mental '
                      'health and substance abuse',
             'Q87.3': 'Residential care activities for the elderly and disabled',
             'Q87.9': 'Other residential care activities',
             'Q88.1': 'Social work activities without accommodation for the elderly '
                      'and disabled',
             'Q88.9': 'Other social work activities without accommodation',
             'R90.0': 'Creative, arts and entertainment activities',
             'R91.0': 'Libraries, archives, museums and other cultural activities',
             'R92.0': 'Gambling and betting activities',
             'R93.1': 'Sports activities',
             'R93.2': 'Amusement and recreation activities',
             'S94.1': 'Activities of business, employers and professional membership '
                      'organisations',
             'S94.2': 'Activities of trade unions',
             'S94.9': 'Activities of other membership organisations',
             'S95.1': 'Repair of computers and communication equipment',
             'S95.2': 'Repair of personal and household goods',
             'S96.0': 'Other personal service activities',
             'T97.0': 'Activities of households as employers of domestic personnel',
             'T98.1': 'Undifferentiated goods-producing activities of private '
                      'households for own use',
             'T98.2': 'Undifferentiated service-producing activities of private '
                      'households for own use',
             'U99.0': 'Activities of extraterritorial organisations and bodies'}
