# Copyright (c) 2020 - 2025 Open Risk (https://www.openriskmanagement.com)
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

NUTS3_DICT = {'AT111': 'Mittelburgenland',
              'AT112': 'Nordburgenland',
              'AT113': 'Südburgenland',
              'AT121': 'Mostviertel-Eisenwurzen',
              'AT122': 'Niederösterreich-Süd',
              'AT123': 'Sankt Pölten',
              'AT124': 'Waldviertel',
              'AT125': 'Weinviertel',
              'AT126': 'Wiener Umland/Nordteil',
              'AT127': 'Wiener Umland/Südteil',
              'AT130': 'Wien',
              'AT211': 'Klagenfurt-Villach',
              'AT212': 'Oberkärnten',
              'AT213': 'Unterkärnten',
              'AT221': 'Graz',
              'AT222': 'Liezen',
              'AT223': 'Östliche Obersteiermark',
              'AT224': 'Oststeiermark',
              'AT225': 'West- und Südsteiermark',
              'AT226': 'Westliche Obersteiermark',
              'AT311': 'Innviertel',
              'AT312': 'Linz-Wels',
              'AT313': 'Mühlviertel',
              'AT314': 'Steyr-Kirchdorf',
              'AT315': 'Traunviertel',
              'AT321': 'Lungau',
              'AT322': 'Pinzgau-Pongau',
              'AT323': 'Salzburg und Umgebung',
              'AT331': 'Außerfern',
              'AT332': 'Innsbruck',
              'AT333': 'Osttirol',
              'AT334': 'Tiroler Oberland',
              'AT335': 'Tiroler Unterland',
              'AT341': 'Bludenz-Bregenzer Wald',
              'AT342': 'Rheintal-Bodenseegebiet',
              'BE100': 'Arr. de Bruxelles-Capitale / Arr. van Brussel-Hoofdstad',
              'BE211': 'Arr. Antwerpen',
              'BE212': 'Arr. Mechelen',
              'BE213': 'Arr. Turnhout',
              'BE221': 'Arr. Hasselt',
              'BE222': 'Arr. Maaseik',
              'BE223': 'Arr. Tongeren',
              'BE231': 'Arr. Aalst',
              'BE232': 'Arr. Dendermonde',
              'BE233': 'Arr. Eeklo',
              'BE234': 'Arr. Gent',
              'BE235': 'Arr. Oudenaarde',
              'BE236': 'Arr. Sint-Niklaas',
              'BE241': 'Arr. Halle-Vilvoorde',
              'BE242': 'Arr. Leuven',
              'BE251': 'Arr. Brugge',
              'BE252': 'Arr. Diksmuide',
              'BE253': 'Arr. Ieper',
              'BE254': 'Arr. Kortrijk',
              'BE255': 'Arr. Oostende',
              'BE256': 'Arr. Roeselare',
              'BE257': 'Arr. Tielt',
              'BE258': 'Arr. Veurne',
              'BE310': 'Arr. Nivelles',
              'BE321': 'Arr. Ath',
              'BE322': 'Arr. Charleroi',
              'BE323': 'Arr. Mons',
              'BE324': 'Arr. Mouscron',
              'BE325': 'Arr. Soignies',
              'BE326': 'Arr. Thuin',
              'BE327': 'Arr. Tournai',
              'BE331': 'Arr. Huy',
              'BE332': 'Arr. Liège',
              'BE334': 'Arr. Waremme',
              'BE335': 'Arr. Verviers - communes francophones',
              'BE336': 'Bezirk Verviers - Deutschsprachige Gemeinschaft',
              'BE341': 'Arr. Arlon',
              'BE342': 'Arr. Bastogne',
              'BE343': 'Arr. Marche-en-Famenne',
              'BE344': 'Arr. Neufchâteau',
              'BE345': 'Arr. Virton',
              'BE351': 'Arr. Dinant',
              'BE352': 'Arr. Namur',
              'BE353': 'Arr. Philippeville',
              'BG311': 'Vidin',
              'BG312': 'Montana',
              'BG313': 'Vratsa',
              'BG314': 'Pleven',
              'BG315': 'Lovech',
              'BG321': 'Veliko Tarnovo',
              'BG322': 'Gabrovo',
              'BG323': 'Ruse',
              'BG324': 'Razgrad',
              'BG325': 'Silistra',
              'BG331': 'Varna',
              'BG332': 'Dobrich',
              'BG333': 'Shumen',
              'BG334': 'Targovishte',
              'BG341': 'Burgas',
              'BG342': 'Sliven',
              'BG343': 'Yambol',
              'BG344': 'Stara Zagora',
              'BG411': 'Sofia (stolitsa)',
              'BG412': 'Sofia',
              'BG413': 'Blagoevgrad',
              'BG414': 'Pernik',
              'BG415': 'Kyustendil',
              'BG421': 'Plovdiv',
              'BG422': 'Haskovo',
              'BG423': 'Pazardzhik',
              'BG424': 'Smolyan',
              'BG425': 'Kardzhali',
              'CY000': 'Kypros',
              'CZ010': 'Hlavní mesto Praha',
              'CZ020': 'Stredoceský  kraj',
              'CZ031': 'Jihocecký kraj',
              'CZ032': 'Plzenský kraj',
              'CZ041': 'Karlovarský kraj',
              'CZ042': 'Ústecký kraj',
              'CZ051': 'Liberecký kraj',
              'CZ052': 'Královéhradecký kraj',
              'CZ053': 'Pardubický kraj',
              'CZ063': 'Kraj Vysocina',
              'CZ064': 'Jihomoravský kraj',
              'CZ071': 'Olomoucký kraj',
              'CZ072': 'Zlínský kraj',
              'CZ080': 'Moravskoslezský kraj',
              'DE111': 'Stuttgart, Stadtkreis',
              'DE112': 'Böblingen',
              'DE113': 'Esslingen',
              'DE114': 'Göppingen',
              'DE115': 'Ludwigsburg',
              'DE116': 'Rems-Murr-Kreis',
              'DE117': 'Heilbronn, Stadtkreis',
              'DE118': 'Heilbronn, Landkreis',
              'DE119': 'Hohenlohekreis',
              'DE11A': 'Schwäbisch Hall',
              'DE11B': 'Main-Tauber-Kreis',
              'DE11C': 'Heidenheim',
              'DE11D': 'Ostalbkreis',
              'DE121': 'Baden-Baden, Stadtkreis',
              'DE122': 'Karlsruhe, Stadtkreis',
              'DE123': 'Karlsruhe, Landkreis',
              'DE124': 'Rastatt',
              'DE125': 'Heidelberg, Stadtkreis',
              'DE126': 'Mannheim, Stadtkreis',
              'DE127': 'Neckar-Odenwald-Kreis',
              'DE128': 'Rhein-Neckar-Kreis',
              'DE129': 'Pforzheim, Stadtkreis',
              'DE12A': 'Calw',
              'DE12B': 'Enzkreis',
              'DE12C': 'Freudenstadt',
              'DE131': 'Freiburg im Breisgau, Stadtkreis',
              'DE132': 'Breisgau-Hochschwarzwald',
              'DE133': 'Emmendingen',
              'DE134': 'Ortenaukreis',
              'DE135': 'Rottweil',
              'DE136': 'Schwarzwald-Baar-Kreis',
              'DE137': 'Tuttlingen',
              'DE138': 'Konstanz',
              'DE139': 'Lörrach',
              'DE13A': 'Waldshut',
              'DE141': 'Reutlingen',
              'DE142': 'Tübingen, Landkreis',
              'DE143': 'Zollernalbkreis',
              'DE144': 'Ulm, Stadtkreis',
              'DE145': 'Alb-Donau-Kreis',
              'DE146': 'Biberach',
              'DE147': 'Bodenseekreis',
              'DE148': 'Ravensburg',
              'DE149': 'Sigmaringen',
              'DE211': 'Ingolstadt, Kreisfreie Stadt',
              'DE212': 'München, Kreisfreie Stadt',
              'DE213': 'Rosenheim, Kreisfreie Stadt',
              'DE214': 'Altötting',
              'DE215': 'Berchtesgadener Land',
              'DE216': 'Bad Tölz-Wolfratshausen',
              'DE217': 'Dachau',
              'DE218': 'Ebersberg',
              'DE219': 'Eichstätt',
              'DE21A': 'Erding',
              'DE21B': 'Freising',
              'DE21C': 'Fürstenfeldbruck',
              'DE21D': 'Garmisch-Partenkirchen',
              'DE21E': 'Landsberg am Lech',
              'DE21F': 'Miesbach',
              'DE21G': 'Mühldorf am Inn',
              'DE21H': 'München, Landkreis',
              'DE21I': 'Neuburg-Schrobenhausen',
              'DE21J': 'Pfaffenhofen an der Ilm',
              'DE21K': 'Rosenheim, Landkreis',
              'DE21L': 'Starnberg',
              'DE21M': 'Traunstein',
              'DE21N': 'Weilheim-Schongau',
              'DE221': 'Landshut, Kreisfreie Stadt',
              'DE222': 'Passau, Kreisfreie Stadt',
              'DE223': 'Straubing, Kreisfreie Stadt',
              'DE224': 'Deggendorf',
              'DE225': 'Freyung-Grafenau',
              'DE226': 'Kelheim',
              'DE227': 'Landshut, Landkreis',
              'DE228': 'Passau, Landkreis',
              'DE229': 'Regen',
              'DE22A': 'Rottal-Inn',
              'DE22B': 'Straubing-Bogen',
              'DE22C': 'Dingolfing-Landau',
              'DE231': 'Amberg, Kreisfreie Stadt',
              'DE232': 'Regensburg, Kreisfreie Stadt',
              'DE233': 'Weiden in der Oberpfalz, Kreisfreie Stadt',
              'DE234': 'Amberg-Sulzbach',
              'DE235': 'Cham',
              'DE236': 'Neumarkt in der Oberpfalz',
              'DE237': 'Neustadt an der Waldnaab',
              'DE238': 'Regensburg, Landkreis',
              'DE239': 'Schwandorf',
              'DE23A': 'Tirschenreuth',
              'DE241': 'Bamberg, Kreisfreie Stadt',
              'DE242': 'Bayreuth, Kreisfreie Stadt',
              'DE243': 'Coburg, Kreisfreie Stadt',
              'DE244': 'Hof, Kreisfreie Stadt',
              'DE245': 'Bamberg, Landkreis',
              'DE246': 'Bayreuth, Landkreis',
              'DE247': 'Coburg, Landkreis',
              'DE248': 'Forchheim',
              'DE249': 'Hof, Landkreis',
              'DE24A': 'Kronach',
              'DE24B': 'Kulmbach',
              'DE24C': 'Lichtenfels',
              'DE24D': 'Wunsiedel im Fichtelgebirge',
              'DE251': 'Ansbach, Kreisfreie Stadt',
              'DE252': 'Erlangen, Kreisfreie Stadt',
              'DE253': 'Fürth, Kreisfreie Stadt',
              'DE254': 'Nürnberg, Kreisfreie Stadt',
              'DE255': 'Schwabach, Kreisfreie Stadt',
              'DE256': 'Ansbach, Landkreis',
              'DE257': 'Erlangen-Höchstadt',
              'DE258': 'Fürth, Landkreis',
              'DE259': 'Nürnberger Land',
              'DE25A': 'Neustadt an der Aisch-Bad Windsheim',
              'DE25B': 'Roth',
              'DE25C': 'Weißenburg-Gunzenhausen',
              'DE261': 'Aschaffenburg, Kreisfreie Stadt',
              'DE262': 'Schweinfurt, Kreisfreie Stadt',
              'DE263': 'Würzburg, Kreisfreie Stadt',
              'DE264': 'Aschaffenburg, Landkreis',
              'DE265': 'Bad Kissingen',
              'DE266': 'Rhön-Grabfeld',
              'DE267': 'Haßberge',
              'DE268': 'Kitzingen',
              'DE269': 'Miltenberg',
              'DE26A': 'Main-Spessart',
              'DE26B': 'Schweinfurt, Landkreis',
              'DE26C': 'Würzburg, Landkreis',
              'DE271': 'Augsburg, Kreisfreie Stadt',
              'DE272': 'Kaufbeuren, Kreisfreie Stadt',
              'DE273': 'Kempten (Allgäu), Kreisfreie Stadt',
              'DE274': 'Memmingen, Kreisfreie Stadt',
              'DE275': 'Aichach-Friedberg',
              'DE276': 'Augsburg, Landkreis',
              'DE277': 'Dillingen an der Donau',
              'DE278': 'Günzburg',
              'DE279': 'Neu-Ulm',
              'DE27A': 'Lindau (Bodensee)',
              'DE27B': 'Ostallgäu',
              'DE27C': 'Unterallgäu',
              'DE27D': 'Donau-Ries',
              'DE27E': 'Oberallgäu',
              'DE300': 'Berlin',
              'DE401': 'Brandenburg an der Havel, Kreisfreie Stadt',
              'DE402': 'Cottbus, Kreisfreie Stadt',
              'DE403': 'Frankfurt (Oder), Kreisfreie Stadt',
              'DE404': 'Potsdam, Kreisfreie Stadt',
              'DE405': 'Barnim',
              'DE406': 'Dahme-Spreewald',
              'DE407': 'Elbe-Elster',
              'DE408': 'Havelland',
              'DE409': 'Märkisch-Oderland',
              'DE40A': 'Oberhavel',
              'DE40B': 'Oberspreewald-Lausitz',
              'DE40C': 'Oder-Spree',
              'DE40D': 'Ostprignitz-Ruppin',
              'DE40E': 'Potsdam-Mittelmark',
              'DE40F': 'Prignitz',
              'DE40G': 'Spree-Neiße',
              'DE40H': 'Teltow-Fläming',
              'DE40I': 'Uckermark',
              'DE501': 'Bremen, Kreisfreie Stadt',
              'DE502': 'Bremerhaven, Kreisfreie Stadt',
              'DE600': 'Hamburg',
              'DE711': 'Darmstadt, Kreisfreie Stadt',
              'DE712': 'Frankfurt am Main, Kreisfreie Stadt',
              'DE713': 'Offenbach am Main, Kreisfreie Stadt',
              'DE714': 'Wiesbaden, Kreisfreie Stadt',
              'DE715': 'Bergstraße',
              'DE716': 'Darmstadt-Dieburg',
              'DE717': 'Groß-Gerau',
              'DE718': 'Hochtaunuskreis',
              'DE719': 'Main-Kinzig-Kreis',
              'DE71A': 'Main-Taunus-Kreis',
              'DE71B': 'Odenwaldkreis',
              'DE71C': 'Offenbach, Landkreis',
              'DE71D': 'Rheingau-Taunus-Kreis',
              'DE71E': 'Wetteraukreis',
              'DE721': 'Gießen, Landkreis',
              'DE722': 'Lahn-Dill-Kreis',
              'DE723': 'Limburg-Weilburg',
              'DE724': 'Marburg-Biedenkopf',
              'DE725': 'Vogelsbergkreis',
              'DE731': 'Kassel, Kreisfreie Stadt',
              'DE732': 'Fulda',
              'DE733': 'Hersfeld-Rotenburg',
              'DE734': 'Kassel, Landkreis',
              'DE735': 'Schwalm-Eder-Kreis',
              'DE736': 'Waldeck-Frankenberg',
              'DE737': 'Werra-Meißner-Kreis',
              'DE801': 'Greifswald, Kreisfreie Stadt',
              'DE802': 'Neubrandenburg, Kreisfreie Stadt',
              'DE803': 'Rostock, Kreisfreie Stadt',
              'DE804': 'Schwerin, Kreisfreie Stadt',
              'DE805': 'Stralsund, Kreisfreie Stadt',
              'DE806': 'Wismar, Kreisfreie Stadt',
              'DE807': 'Bad Doberan',
              'DE808': 'Demmin',
              'DE809': 'Güstrow',
              'DE80A': 'Ludwigslust',
              'DE80B': 'Mecklenburg-Strelitz',
              'DE80C': 'Müritz',
              'DE80D': 'Nordvorpommern',
              'DE80E': 'Nordwestmecklenburg',
              'DE80F': 'Ostvorpommern',
              'DE80G': 'Parchim',
              'DE80H': 'Rügen',
              'DE80I': 'Uecker-Randow',
              'DE911': 'Braunschweig, Kreisfreie Stadt',
              'DE912': 'Salzgitter, Kreisfreie Stadt',
              'DE913': 'Wolfsburg, Kreisfreie Stadt',
              'DE914': 'Gifhorn',
              'DE915': 'Göttingen',
              'DE916': 'Goslar',
              'DE917': 'Helmstedt',
              'DE918': 'Northeim',
              'DE919': 'Osterode am Harz',
              'DE91A': 'Peine',
              'DE91B': 'Wolfenbüttel',
              'DE922': 'Diepholz',
              'DE923': 'Hameln-Pyrmont',
              'DE925': 'Hildesheim',
              'DE926': 'Holzminden',
              'DE927': 'Nienburg (Weser)',
              'DE928': 'Schaumburg',
              'DE929': 'Region Hannover',
              'DE931': 'Celle',
              'DE932': 'Cuxhaven',
              'DE933': 'Harburg',
              'DE934': 'Lüchow-Dannenberg',
              'DE935': 'Lüneburg, Landkreis',
              'DE936': 'Osterholz',
              'DE937': 'Rotenburg (Wümme)',
              'DE938': 'Soltau-Fallingbostel',
              'DE939': 'Stade',
              'DE93A': 'Uelzen',
              'DE93B': 'Verden',
              'DE941': 'Delmenhorst, Kreisfreie Stadt',
              'DE942': 'Emden, Kreisfreie Stadt',
              'DE943': 'Oldenburg (Oldenburg), Kreisfreie Stadt',
              'DE944': 'Osnabrück, Kreisfreie Stadt',
              'DE945': 'Wilhelmshaven, Kreisfreie Stadt',
              'DE946': 'Ammerland',
              'DE947': 'Aurich',
              'DE948': 'Cloppenburg',
              'DE949': 'Emsland',
              'DE94A': 'Friesland (DE)',
              'DE94B': 'Grafschaft Bentheim',
              'DE94C': 'Leer',
              'DE94D': 'Oldenburg, Landkreis',
              'DE94E': 'Osnabrück, Landkreis',
              'DE94F': 'Vechta',
              'DE94G': 'Wesermarsch',
              'DE94H': 'Wittmund',
              'DEA11': 'Düsseldorf, Kreisfreie Stadt',
              'DEA12': 'Duisburg, Kreisfreie Stadt',
              'DEA13': 'Essen, Kreisfreie Stadt',
              'DEA14': 'Krefeld, Kreisfreie Stadt',
              'DEA15': 'Mönchengladbach, Kreisfreie Stadt',
              'DEA16': 'Mülheim an der Ruhr, Kreisfreie Stadt',
              'DEA17': 'Oberhausen, Kreisfreie Stadt',
              'DEA18': 'Remscheid, Kreisfreie Stadt',
              'DEA19': 'Solingen, Kreisfreie Stadt',
              'DEA1A': 'Wuppertal, Kreisfreie Stadt',
              'DEA1B': 'Kleve',
              'DEA1C': 'Mettmann',
              'DEA1D': 'Rhein-Kreis Neuss',
              'DEA1E': 'Viersen',
              'DEA1F': 'Wesel',
              'DEA22': 'Bonn, Kreisfreie Stadt',
              'DEA23': 'Köln, Kreisfreie Stadt',
              'DEA24': 'Leverkusen, Kreisfreie Stadt',
              'DEA26': 'Düren',
              'DEA27': 'Rhein-Erft-Kreis',
              'DEA28': 'Euskirchen',
              'DEA29': 'Heinsberg',
              'DEA2A': 'Oberbergischer Kreis',
              'DEA2B': 'Rheinisch-Bergischer Kreis',
              'DEA2C': 'Rhein-Sieg-Kreis',
              'DEA2D': 'Städteregion Aachen',
              'DEA31': 'Bottrop, Kreisfreie Stadt',
              'DEA32': 'Gelsenkirchen, Kreisfreie Stadt',
              'DEA33': 'Münster, Kreisfreie Stadt',
              'DEA34': 'Borken',
              'DEA35': 'Coesfeld',
              'DEA36': 'Recklinghausen',
              'DEA37': 'Steinfurt',
              'DEA38': 'Warendorf',
              'DEA41': 'Bielefeld, Kreisfreie Stadt',
              'DEA42': 'Gütersloh',
              'DEA43': 'Herford',
              'DEA44': 'Höxter',
              'DEA45': 'Lippe',
              'DEA46': 'Minden-Lübbecke',
              'DEA47': 'Paderborn',
              'DEA51': 'Bochum, Kreisfreie Stadt',
              'DEA52': 'Dortmund, Kreisfreie Stadt',
              'DEA53': 'Hagen, Kreisfreie Stadt',
              'DEA54': 'Hamm, Kreisfreie Stadt',
              'DEA55': 'Herne, Kreisfreie Stadt',
              'DEA56': 'Ennepe-Ruhr-Kreis',
              'DEA57': 'Hochsauerlandkreis',
              'DEA58': 'Märkischer Kreis',
              'DEA59': 'Olpe',
              'DEA5A': 'Siegen-Wittgenstein',
              'DEA5B': 'Soest',
              'DEA5C': 'Unna',
              'DEB11': 'Koblenz, Kreisfreie Stadt',
              'DEB12': 'Ahrweiler',
              'DEB13': 'Altenkirchen (Westerwald)',
              'DEB14': 'Bad Kreuznach',
              'DEB15': 'Birkenfeld',
              'DEB16': 'Cochem-Zell',
              'DEB17': 'Mayen-Koblenz',
              'DEB18': 'Neuwied',
              'DEB19': 'Rhein-Hunsrück-Kreis',
              'DEB1A': 'Rhein-Lahn-Kreis',
              'DEB1B': 'Westerwaldkreis',
              'DEB21': 'Trier, Kreisfreie Stadt',
              'DEB22': 'Bernkastel-Wittlich',
              'DEB23': 'Eifelkreis Bitburg-Prüm',
              'DEB24': 'Vulkaneifel',
              'DEB25': 'Trier-Saarburg',
              'DEB31': 'Frankenthal (Pfalz), Kreisfreie Stadt',
              'DEB32': 'Kaiserslautern, Kreisfreie Stadt',
              'DEB33': 'Landau in der Pfalz, Kreisfreie Stadt',
              'DEB34': 'Ludwigshafen am Rhein, Kreisfreie Stadt',
              'DEB35': 'Mainz, Kreisfreie Stadt',
              'DEB36': 'Neustadt an der Weinstraße, Kreisfreie Stadt',
              'DEB37': 'Pirmasens, Kreisfreie Stadt',
              'DEB38': 'Speyer, Kreisfreie Stadt',
              'DEB39': 'Worms, Kreisfreie Stadt',
              'DEB3A': 'Zweibrücken, Kreisfreie Stadt',
              'DEB3B': 'Alzey-Worms',
              'DEB3C': 'Bad Dürkheim',
              'DEB3D': 'Donnersbergkreis',
              'DEB3E': 'Germersheim',
              'DEB3F': 'Kaiserslautern, Landkreis',
              'DEB3G': 'Kusel',
              'DEB3H': 'Südliche Weinstraße',
              'DEB3I': 'Rhein-Pfalz-Kreis',
              'DEB3J': 'Mainz-Bingen',
              'DEB3K': 'Südwestpfalz',
              'DEC01': 'Regionalverband Saarbrücken',
              'DEC02': 'Merzig-Wadern',
              'DEC03': 'Neunkirchen',
              'DEC04': 'Saarlouis',
              'DEC05': 'Saarpfalz-Kreis',
              'DEC06': 'St. Wendel',
              'DED21': 'Dresden, Kreisfreie Stadt',
              'DED2C': 'Bautzen',
              'DED2D': 'Görlitz',
              'DED2E': 'Meißen',
              'DED2F': 'Sächsische Schweiz-Osterzgebirge',
              'DED41': 'Chemnitz, Kreisfreie Stadt',
              'DED42': 'Erzgebirgskreis',
              'DED43': 'Mittelsachsen',
              'DED44': 'Vogtlandkreis',
              'DED45': 'Zwickau',
              'DED51': 'Leipzig, Kreisfreie Stadt',
              'DED52': 'Leipzig',
              'DED53': 'Nordsachsen',
              'DEE01': 'Dessau-Roßlau, Kreisfreie Stadt',
              'DEE02': 'Halle (Saale), Kreisfreie Stadt',
              'DEE03': 'Magdeburg, Kreisfreie Stadt',
              'DEE04': 'Altmarkkreis Salzwedel',
              'DEE05': 'Anhalt-Bitterfeld',
              'DEE06': 'Jerichower Land',
              'DEE07': 'Börde',
              'DEE08': 'Burgenland (DE)',
              'DEE09': 'Harz',
              'DEE0A': 'Mansfeld-Südharz',
              'DEE0B': 'Saalekreis',
              'DEE0C': 'Salzlandkreis',
              'DEE0D': 'Stendal',
              'DEE0E': 'Wittenberg',
              'DEF01': 'Flensburg, Kreisfreie Stadt',
              'DEF02': 'Kiel, Kreisfreie Stadt',
              'DEF03': 'Lübeck, Kreisfreie Stadt',
              'DEF04': 'Neumünster, Kreisfreie Stadt',
              'DEF05': 'Dithmarschen',
              'DEF06': 'Herzogtum Lauenburg',
              'DEF07': 'Nordfriesland',
              'DEF08': 'Ostholstein',
              'DEF09': 'Pinneberg',
              'DEF0A': 'Plön',
              'DEF0B': 'Rendsburg-Eckernförde',
              'DEF0C': 'Schleswig-Flensburg',
              'DEF0D': 'Segeberg',
              'DEF0E': 'Steinburg',
              'DEF0F': 'Stormarn',
              'DEG01': 'Erfurt, Kreisfreie Stadt',
              'DEG02': 'Gera, Kreisfreie Stadt',
              'DEG03': 'Jena, Kreisfreie Stadt',
              'DEG04': 'Suhl, Kreisfreie Stadt',
              'DEG05': 'Weimar, Kreisfreie Stadt',
              'DEG06': 'Eichsfeld',
              'DEG07': 'Nordhausen',
              'DEG09': 'Unstrut-Hainich-Kreis',
              'DEG0A': 'Kyffhäuserkreis',
              'DEG0B': 'Schmalkalden-Meiningen',
              'DEG0C': 'Gotha',
              'DEG0D': 'Sömmerda',
              'DEG0E': 'Hildburghausen',
              'DEG0F': 'Ilm-Kreis',
              'DEG0G': 'Weimarer Land',
              'DEG0H': 'Sonneberg',
              'DEG0I': 'Saalfeld-Rudolstadt',
              'DEG0J': 'Saale-Holzland-Kreis',
              'DEG0K': 'Saale-Orla-Kreis',
              'DEG0L': 'Greiz',
              'DEG0M': 'Altenburger Land',
              'DEG0N': 'Eisenach, Kreisfreie Stadt',
              'DEG0P': 'Wartburgkreis',
              'DK011': 'Byen København',
              'DK012': 'Københavns omegn',
              'DK013': 'Nordsjælland',
              'DK014': 'Bornholm',
              'DK021': 'Østsjælland',
              'DK022': 'Vest- og Sydsjælland',
              'DK031': 'Fyn',
              'DK032': 'Sydjylland',
              'DK041': 'Vestjylland',
              'DK042': 'Østjylland',
              'DK050': 'Nordjylland',
              'EE001': 'Põhja-Eesti',
              'EE004': 'Lääne-Eesti',
              'EE006': 'Kesk-Eesti',
              'EE007': 'Kirde-Eesti',
              'EE008': 'Lõuna-Eesti',
              'EL111': 'Evros',
              'EL112': 'Xanthi',
              'EL113': 'Rodopi',
              'EL114': 'Drama',
              'EL115': 'Kavala',
              'EL121': 'Imathia',
              'EL122': 'Thessaloniki',
              'EL123': 'Kilkis',
              'EL124': 'Pella',
              'EL125': 'Pieria',
              'EL126': 'Serres',
              'EL127': 'Chalkidiki',
              'EL131': 'Grevena',
              'EL132': 'Kastoria',
              'EL133': 'Kozani',
              'EL134': 'Florina',
              'EL141': 'Karditsa',
              'EL142': 'Larisa',
              'EL143': 'Magnisia',
              'EL144': 'Trikala',
              'EL211': 'Arta',
              'EL212': 'Thesprotia',
              'EL213': 'Ioannina',
              'EL214': 'Preveza',
              'EL221': 'Zakynthos',
              'EL222': 'Kerkyra',
              'EL223': 'Kefallinia',
              'EL224': 'Lefkada',
              'EL231': 'Aitoloakarnania',
              'EL232': 'Achaia',
              'EL233': 'Ileia',
              'EL241': 'Voiotia',
              'EL242': 'Evvoia',
              'EL243': 'Evrytania',
              'EL244': 'Fthiotida',
              'EL245': 'Fokida',
              'EL251': 'Argolida',
              'EL252': 'Arkadia',
              'EL253': 'Korinthia',
              'EL254': 'Lakonia',
              'EL255': 'Messinia',
              'EL300': 'Attiki',
              'EL411': 'Lesvos',
              'EL412': 'Samos',
              'EL413': 'Chios',
              'EL421': 'Dodekanisos',
              'EL422': 'Kyklades',
              'EL431': 'Irakleio',
              'EL432': 'Lasithi',
              'EL433': 'Rethymni',
              'EL434': 'Chania',
              'ES111': 'A Coruña',
              'ES112': 'Lugo',
              'ES113': 'Ourense',
              'ES114': 'Pontevedra',
              'ES120': 'Asturias',
              'ES130': 'Cantabria',
              'ES211': 'Álava',
              'ES212': 'Guipúzcoa',
              'ES213': 'Vizcaya',
              'ES220': 'Navarra',
              'ES230': 'La Rioja',
              'ES241': 'Huesca',
              'ES242': 'Teruel',
              'ES243': 'Zaragoza',
              'ES300': 'Madrid',
              'ES411': 'Ávila',
              'ES412': 'Burgos',
              'ES413': 'León',
              'ES414': 'Palencia',
              'ES415': 'Salamanca',
              'ES416': 'Segovia',
              'ES417': 'Soria',
              'ES418': 'Valladolid',
              'ES419': 'Zamora',
              'ES421': 'Albacete',
              'ES422': 'Ciudad Real',
              'ES423': 'Cuenca',
              'ES424': 'Guadalajara',
              'ES425': 'Toledo',
              'ES431': 'Badajoz',
              'ES432': 'Cáceres',
              'ES511': 'Barcelona',
              'ES512': 'Girona',
              'ES513': 'Lleida',
              'ES514': 'Tarragona',
              'ES521': 'Alicante / Alacant',
              'ES522': 'Castellón / Castelló',
              'ES523': 'Valencia / València',
              'ES531': 'Eivissa, Formentera',
              'ES532': 'Mallorca',
              'ES533': 'Menorca',
              'ES611': 'Almería',
              'ES612': 'Cádiz',
              'ES613': 'Córdoba',
              'ES614': 'Granada',
              'ES615': 'Huelva',
              'ES616': 'Jaén',
              'ES617': 'Málaga',
              'ES618': 'Sevilla',
              'ES620': 'Murcia',
              'ES630': 'Ceuta (ES)',
              'ES640': 'Melilla (ES)',
              'ES703': 'El Hierro',
              'ES704': 'Fuerteventura',
              'ES705': 'Gran Canaria',
              'ES706': 'La Gomera',
              'ES707': 'La Palma',
              'ES708': 'Lanzarote',
              'ES709': 'Tenerife',
              'FI193': 'Keski-Suomi',
              'FI194': 'Etelä-Pohjanmaa',
              'FI195': 'Pohjanmaa',
              'FI196': 'Satakunta',
              'FI197': 'Pirkanmaa',
              'FI1B1': 'Helsinki-Uusimaa',
              'FI1C1': 'Varsinais-Suomi',
              'FI1C2': 'Kanta-Häme',
              'FI1C3': 'Päijät-Häme',
              'FI1C4': 'Kymenlaakso',
              'FI1C5': 'Etelä-Karjala',
              'FI1D1': 'Etelä-Savo',
              'FI1D2': 'Pohjois-Savo',
              'FI1D3': 'Pohjois-Karjala',
              'FI1D4': 'Kainuu',
              'FI1D5': 'Keski-Pohjanmaa',
              'FI1D6': 'Pohjois-Pohjanmaa',
              'FI1D7': 'Lappi',
              'FI200': 'Åland',
              'FR101': 'Paris',
              'FR102': 'Seine-et-Marne',
              'FR103': 'Yvelines',
              'FR104': 'Essonne',
              'FR105': 'Hauts-de-Seine',
              'FR106': 'Seine-Saint-Denis',
              'FR107': 'Val-de-Marne',
              'FR108': "Val-d'Oise",
              'FR211': 'Ardennes',
              'FR212': 'Aube',
              'FR213': 'Marne',
              'FR214': 'Haute-Marne',
              'FR221': 'Aisne',
              'FR222': 'Oise',
              'FR223': 'Somme',
              'FR231': 'Eure',
              'FR232': 'Seine-Maritime',
              'FR241': 'Cher',
              'FR242': 'Eure-et-Loir',
              'FR243': 'Indre',
              'FR244': 'Indre-et-Loire',
              'FR245': 'Loir-et-Cher',
              'FR246': 'Loiret',
              'FR251': 'Calvados',
              'FR252': 'Manche',
              'FR253': 'Orne',
              'FR261': "Côte-d'Or",
              'FR262': 'Nièvre',
              'FR263': 'Saône-et-Loire',
              'FR264': 'Yonne',
              'FR301': 'Nord (FR)',
              'FR302': 'Pas-de-Calais',
              'FR411': 'Meurthe-et-Moselle',
              'FR412': 'Meuse',
              'FR413': 'Moselle',
              'FR414': 'Vosges',
              'FR421': 'Bas-Rhin',
              'FR422': 'Haut-Rhin',
              'FR431': 'Doubs',
              'FR432': 'Jura',
              'FR433': 'Haute-Saône',
              'FR434': 'Territoire de Belfort',
              'FR511': 'Loire-Atlantique',
              'FR512': 'Maine-et-Loire',
              'FR513': 'Mayenne',
              'FR514': 'Sarthe',
              'FR515': 'Vendée',
              'FR521': "Côtes-d'Armor",
              'FR522': 'Finistère',
              'FR523': 'Ille-et-Vilaine',
              'FR524': 'Morbihan',
              'FR531': 'Charente',
              'FR532': 'Charente-Maritime',
              'FR533': 'Deux-Sèvres',
              'FR534': 'Vienne',
              'FR611': 'Dordogne',
              'FR612': 'Gironde',
              'FR613': 'Landes',
              'FR614': 'Lot-et-Garonne',
              'FR615': 'Pyrénées-Atlantiques',
              'FR621': 'Ariège',
              'FR622': 'Aveyron',
              'FR623': 'Haute-Garonne',
              'FR624': 'Gers',
              'FR625': 'Lot',
              'FR626': 'Hautes-Pyrénées',
              'FR627': 'Tarn',
              'FR628': 'Tarn-et-Garonne',
              'FR631': 'Corrèze',
              'FR632': 'Creuse',
              'FR633': 'Haute-Vienne',
              'FR711': 'Ain',
              'FR712': 'Ardèche',
              'FR713': 'Drôme',
              'FR714': 'Isère',
              'FR715': 'Loire',
              'FR716': 'Rhône',
              'FR717': 'Savoie',
              'FR718': 'Haute-Savoie',
              'FR721': 'Allier',
              'FR722': 'Cantal',
              'FR723': 'Haute-Loire',
              'FR724': 'Puy-de-Dôme',
              'FR811': 'Aude',
              'FR812': 'Gard',
              'FR813': 'Hérault',
              'FR814': 'Lozère',
              'FR815': 'Pyrénées-Orientales',
              'FR821': 'Alpes-de-Haute-Provence',
              'FR822': 'Hautes-Alpes',
              'FR823': 'Alpes-Maritimes',
              'FR824': 'Bouches-du-Rhône',
              'FR825': 'Var',
              'FR826': 'Vaucluse',
              'FR831': 'Corse-du-Sud',
              'FR832': 'Haute-Corse',
              'FR910': 'Guadeloupe (FR)',
              'FR920': 'Martinique (FR)',
              'FR930': 'Guyane (FR)',
              'FR940': 'Réunion (FR)',
              'HR031': 'Primorsko-goranska zupanija',
              'HR032': 'Licko-senjska zupanija',
              'HR033': 'Zadarska zupanija',
              'HR034': 'Sibensko-kninska zupanija',
              'HR035': 'Splitsko-dalmatinska zupanija',
              'HR036': 'Istarska zupanija',
              'HR037': 'Dubrovacko-neretvanska zupanija',
              'HR041': 'Grad Zagreb',
              'HR042': 'Zagrebacka zupanija',
              'HR043': 'Krapinsko-zagorska zupanija',
              'HR044': 'Varazdinska zupanija',
              'HR045': 'Koprivnicko-krizevacka zupanija',
              'HR046': 'Medimurska zupanija',
              'HR047': 'Bjelovarsko-bilogorska zupanija',
              'HR048': 'Viroviticko-podravska zupanija',
              'HR049': 'Pozesko-slavonska zupanija',
              'HR04A': 'Brodsko-posavska zupanija',
              'HR04B': 'Osjecko-baranjska zupanija',
              'HR04C': 'Vukovarsko-srijemska zupanija',
              'HR04D': 'Karlovacka zupanija',
              'HR04E': 'Sisacko-moslavacka zupanija',
              'HU101': 'Budapest',
              'HU102': 'Pest',
              'HU211': 'Fejér',
              'HU212': 'Komárom-Esztergom',
              'HU213': 'Veszprém',
              'HU221': 'Gyor-Moson-Sopron',
              'HU222': 'Vas',
              'HU223': 'Zala',
              'HU231': 'Baranya',
              'HU232': 'Somogy',
              'HU233': 'Tolna',
              'HU311': 'Borsod-Abaúj-Zemplén',
              'HU312': 'Heves',
              'HU313': 'Nógrád',
              'HU321': 'Hajdú-Bihar',
              'HU322': 'Jász-Nagykun-Szolnok',
              'HU323': 'Szabolcs-Szatmár-Bereg',
              'HU331': 'Bács-Kiskun',
              'HU332': 'Békés',
              'HU333': 'Csongrád',
              'IE011': 'Border',
              'IE012': 'Midland',
              'IE013': 'West',
              'IE021': 'Dublin',
              'IE022': 'Mid-East',
              'IE023': 'Mid-West',
              'IE024': 'South-East (IE)',
              'IE025': 'South-West (IE)',
              'ITC11': 'Torino',
              'ITC12': 'Vercelli',
              'ITC13': 'Biella',
              'ITC14': 'Verbano-Cusio-Ossola',
              'ITC15': 'Novara',
              'ITC16': 'Cuneo',
              'ITC17': 'Asti',
              'ITC18': 'Alessandria',
              'ITC20': "Valle d'Aosta/Vallée d'Aoste",
              'ITC31': 'Imperia',
              'ITC32': 'Savona',
              'ITC33': 'Genova',
              'ITC34': 'La Spezia',
              'ITC41': 'Varese',
              'ITC42': 'Como',
              'ITC43': 'Lecco',
              'ITC44': 'Sondrio',
              'ITC46': 'Bergamo',
              'ITC47': 'Brescia',
              'ITC48': 'Pavia',
              'ITC49': 'Lodi',
              'ITC4A': 'Cremona',
              'ITC4B': 'Mantova',
              'ITC4C': 'Milano',
              'ITC4D': 'Monza e della Brianza',
              'ITF11': "L'Aquila",
              'ITF12': 'Teramo',
              'ITF13': 'Pescara',
              'ITF14': 'Chieti',
              'ITF21': 'Isernia',
              'ITF22': 'Campobasso',
              'ITF31': 'Caserta',
              'ITF32': 'Benevento',
              'ITF33': 'Napoli',
              'ITF34': 'Avellino',
              'ITF35': 'Salerno',
              'ITF43': 'Taranto',
              'ITF44': 'Brindisi',
              'ITF45': 'Lecce',
              'ITF46': 'Foggia',
              'ITF47': 'Bari',
              'ITF48': 'Barletta-Andria-Trani',
              'ITF51': 'Potenza',
              'ITF52': 'Matera',
              'ITF61': 'Cosenza',
              'ITF62': 'Crotone',
              'ITF63': 'Catanzaro',
              'ITF64': 'Vibo Valentia',
              'ITF65': 'Reggio di Calabria',
              'ITG11': 'Trapani',
              'ITG12': 'Palermo',
              'ITG13': 'Messina',
              'ITG14': 'Agrigento',
              'ITG15': 'Caltanissetta',
              'ITG16': 'Enna',
              'ITG17': 'Catania',
              'ITG18': 'Ragusa',
              'ITG19': 'Siracusa',
              'ITG25': 'Sassari',
              'ITG26': 'Nuoro',
              'ITG27': 'Cagliari',
              'ITG28': 'Oristano',
              'ITG29': 'Olbia-Tempio',
              'ITG2A': 'Ogliastra',
              'ITG2B': 'Medio Campidano',
              'ITG2C': 'Carbonia-Iglesias',
              'ITH10': 'Bolzano-Bozen',
              'ITH20': 'Trento',
              'ITH31': 'Verona',
              'ITH32': 'Vicenza',
              'ITH33': 'Belluno',
              'ITH34': 'Treviso',
              'ITH35': 'Venezia',
              'ITH36': 'Padova',
              'ITH37': 'Rovigo',
              'ITH41': 'Pordenone',
              'ITH42': 'Udine',
              'ITH43': 'Gorizia',
              'ITH44': 'Trieste',
              'ITH51': 'Piacenza',
              'ITH52': 'Parma',
              'ITH53': "Reggio nell'Emilia",
              'ITH54': 'Modena',
              'ITH55': 'Bologna',
              'ITH56': 'Ferrara',
              'ITH57': 'Ravenna',
              'ITH58': 'Forlì-Cesena',
              'ITH59': 'Rimini',
              'ITI11': 'Massa-Carrara',
              'ITI12': 'Lucca',
              'ITI13': 'Pistoia',
              'ITI14': 'Firenze',
              'ITI15': 'Prato',
              'ITI16': 'Livorno',
              'ITI17': 'Pisa',
              'ITI18': 'Arezzo',
              'ITI19': 'Siena',
              'ITI1A': 'Grosseto',
              'ITI21': 'Perugia',
              'ITI22': 'Terni',
              'ITI31': 'Pesaro e Urbino',
              'ITI32': 'Ancona',
              'ITI33': 'Macerata',
              'ITI34': 'Ascoli Piceno',
              'ITI35': 'Fermo',
              'ITI41': 'Viterbo',
              'ITI42': 'Rieti',
              'ITI43': 'Roma',
              'ITI44': 'Latina',
              'ITI45': 'Frosinone',
              'LT001': 'Alytaus apskritis',
              'LT002': 'Kauno apskritis',
              'LT003': 'Klaipėdos apskritis',
              'LT004': 'Marijampolės apskritis',
              'LT005': 'Panevėžio apskritis',
              'LT006': 'Šiaulių apskritis',
              'LT007': 'Tauragės apskritis',
              'LT008': ' Telšių apskritis',
              'LT009': 'Utenos apskritis',
              'LT00A': 'Vilniaus apskritis',
              'LU000': 'Luxembourg',
              'LV003': 'Kurzeme',
              'LV005': 'Latgale',
              'LV006': 'Riga',
              'LV007': 'Pieriga',
              'LV008': 'Vidzeme',
              'LV009': 'Zemgale',
              'MK001': 'Vardarski',
              'MK002': 'Istocen',
              'MK003': 'Jugozapaden',
              'MK004': 'Jugoistocen',
              'MK005': 'Pelagoniski',
              'MK006': 'Poloski',
              'MK007': 'Severoistocen',
              'MK008': 'Skopski',
              'MT001': 'Malta',
              'MT002': 'Gozo and Comino / Ghawdex u Kemmuna',
              'NL111': 'Oost-Groningen',
              'NL112': 'Delfzijl en omgeving',
              'NL113': 'Overig Groningen',
              'NL121': 'Noord-Friesland',
              'NL122': 'Zuidwest-Friesland',
              'NL123': 'Zuidoost-Friesland',
              'NL131': 'Noord-Drenthe',
              'NL132': 'Zuidoost-Drenthe',
              'NL133': 'Zuidwest-Drenthe',
              'NL211': 'Noord-Overijssel',
              'NL212': 'Zuidwest-Overijssel',
              'NL213': 'Twente',
              'NL221': 'Veluwe',
              'NL224': 'Zuidwest-Gelderland',
              'NL225': 'Achterhoek',
              'NL226': 'Arnhem/Nijmegen',
              'NL230': 'Flevoland',
              'NL310': 'Utrecht',
              'NL321': 'Kop van Noord-Holland',
              'NL322': 'Alkmaar en omgeving',
              'NL323': 'IJmond',
              'NL324': 'Agglomeratie Haarlem',
              'NL325': 'Zaanstreek',
              'NL326': 'Groot-Amsterdam',
              'NL327': 'Het Gooi en Vechtstreek',
              'NL332': "Agglomeratie 's-Gravenhage",
              'NL333': 'Delft en Westland',
              'NL337': 'Agglomeratie Leiden en Bollenstreek',
              'NL338': 'Oost-Zuid-Holland',
              'NL339': 'Groot-Rijnmond',
              'NL33A': 'Zuidoost-Zuid-Holland',
              'NL341': 'Zeeuwsch-Vlaanderen',
              'NL342': 'Overig Zeeland',
              'NL411': 'West-Noord-Brabant',
              'NL412': 'Midden-Noord-Brabant',
              'NL413': 'Noordoost-Noord-Brabant',
              'NL414': 'Zuidoost-Noord-Brabant',
              'NL421': 'Noord-Limburg',
              'NL422': 'Midden-Limburg',
              'NL423': 'Zuid-Limburg',
              'NO011': 'Oslo',
              'NO012': 'Akershus',
              'NO021': 'Hedmark',
              'NO022': 'Oppland',
              'NO031': 'Østfold',
              'NO032': 'Buskerud',
              'NO033': 'Vestfold',
              'NO034': 'Telemark',
              'NO041': 'Aust-Agder',
              'NO042': 'Vest-Agder',
              'NO043': 'Rogaland',
              'NO051': 'Hordaland',
              'NO052': 'Sogn og Fjordane',
              'NO053': 'Møre og Romsdal',
              'NO061': 'Sør-Trøndelag',
              'NO062': 'Nord-Trøndelag',
              'NO071': 'Nordland',
              'NO072': 'Troms',
              'NO073': 'Finnmark',
              'PL113': 'Miasto Lódz',
              'PL114': 'Lódzki',
              'PL115': 'Piotrkowski',
              'PL116': 'Sieradzki',
              'PL117': 'Skierniewicki',
              'PL121': 'Ciechanowsko-plocki',
              'PL122': 'Ostrolecko-siedlecki',
              'PL127': 'Miasto Warszawa',
              'PL128': 'Radomski',
              'PL129': 'Warszawski-wschodni',
              'PL12A': 'Warszawski-zachodni',
              'PL213': 'Miasto Kraków',
              'PL214': 'Krakowski',
              'PL215': 'Nowosadecki',
              'PL216': 'Oswiecimski',
              'PL217': 'Tarnowski',
              'PL224': 'Czestochowski',
              'PL225': 'Bielski',
              'PL227': 'Rybnicki',
              'PL228': 'Bytomski',
              'PL229': 'Gliwicki',
              'PL22A': 'Katowicki',
              'PL22B': 'Sosnowiecki',
              'PL22C': 'Tyski',
              'PL311': 'Bialski',
              'PL312': 'Chelmsko-zamojski',
              'PL314': 'Lubelski',
              'PL315': 'Pulawski',
              'PL323': 'Krosnienski',
              'PL324': 'Przemyski',
              'PL325': 'Rzeszowski',
              'PL326': 'Tarnobrzeski',
              'PL331': 'Kielecki',
              'PL332': 'Sandomiersko-jedrzejowski',
              'PL343': 'Bialostocki',
              'PL344': 'Lomzynski',
              'PL345': 'Suwalski',
              'PL411': 'Pilski',
              'PL414': 'Koninski',
              'PL415': 'Miasto Poznan',
              'PL416': 'Kaliski',
              'PL417': 'Leszczynski',
              'PL418': 'Poznanski',
              'PL422': 'Koszalinski',
              'PL423': 'Stargardzki',
              'PL424': 'Miasto Szczecin',
              'PL425': 'Szczecinski',
              'PL431': 'Gorzowski',
              'PL432': 'Zielonogórski',
              'PL514': 'Miasto Wroclaw',
              'PL515': 'Jeleniogórski',
              'PL516': 'Legnicko-Glogowski',
              'PL517': 'Walbrzyski',
              'PL518': 'Wroclawski',
              'PL521': 'Nyski',
              'PL522': 'Opolski',
              'PL613': 'Bydgosko-Torunski',
              'PL614': 'Grudziadzki',
              'PL615': 'Wloclawski',
              'PL621': 'Elblaski',
              'PL622': 'Olsztynski',
              'PL623': 'Elcki',
              'PL631': 'Slupski',
              'PL633': 'Trojmiejski',
              'PL634': 'Gdanski',
              'PL635': 'Starogardzki',
              'PT111': 'Minho-Lima',
              'PT112': 'Cávado',
              'PT113': 'Ave',
              'PT114': 'Grande Porto',
              'PT115': 'Tâmega',
              'PT116': 'Entre Douro e Vouga',
              'PT117': 'Douro',
              'PT118': 'Alto Trás-os-Montes',
              'PT150': 'Algarve',
              'PT161': 'Baixo Vouga',
              'PT162': 'Baixo Mondego',
              'PT163': 'Pinhal Litoral',
              'PT164': 'Pinhal Interior Norte',
              'PT165': 'Dão-Lafões',
              'PT166': 'Pinhal Interior Sul',
              'PT167': 'Serra da Estrela',
              'PT168': 'Beira Interior Norte',
              'PT169': 'Beira Interior Sul',
              'PT16A': 'Cova da Beira',
              'PT16B': 'Oeste',
              'PT16C': 'Médio Tejo',
              'PT171': 'Grande Lisboa',
              'PT172': 'Península de Setúbal',
              'PT181': 'Alentejo Litoral',
              'PT182': 'Alto Alentejo',
              'PT183': 'Alentejo Central',
              'PT184': 'Baixo Alentejo',
              'PT185': 'Lezíria do Tejo',
              'PT200': 'Região Autónoma dos Açores (PT)',
              'PT300': 'Região Autónoma da Madeira (PT)',
              'RO111': 'Bihor',
              'RO112': 'Bistrita-Nasaud',
              'RO113': 'Cluj',
              'RO114': 'Maramures',
              'RO115': 'Satu Mare',
              'RO116': 'Salaj',
              'RO121': 'Alba',
              'RO122': 'Brasov',
              'RO123': 'Covasna',
              'RO124': 'Harghita',
              'RO125': 'Mures',
              'RO126': 'Sibiu',
              'RO211': 'Bacau',
              'RO212': 'Botosani',
              'RO213': 'Iasi',
              'RO214': 'Neamt',
              'RO215': 'Suceava',
              'RO216': 'Vaslui',
              'RO221': 'Braila',
              'RO222': 'Buzau',
              'RO223': 'Constanta',
              'RO224': 'Galati',
              'RO225': 'Tulcea',
              'RO226': 'Vrancea',
              'RO311': 'Arges',
              'RO312': 'Calarasi',
              'RO313': 'Dâmbovita',
              'RO314': 'Giurgiu',
              'RO315': 'Ialomita',
              'RO316': 'Prahova',
              'RO317': 'Teleorman',
              'RO321': 'Bucuresti',
              'RO322': 'Ilfov',
              'RO411': 'Dolj',
              'RO412': 'Gorj',
              'RO413': 'Mehedinti',
              'RO414': 'Olt',
              'RO415': 'Vâlcea',
              'RO421': 'Arad',
              'RO422': 'Caras-Severin',
              'RO423': 'Hunedoara',
              'RO424': 'Timis',
              'SE110': 'Stockholms län',
              'SE121': 'Uppsala län',
              'SE122': 'Södermanlands län',
              'SE123': 'Östergötlands län',
              'SE124': 'Örebro län',
              'SE125': 'Västmanlands län',
              'SE211': 'Jönköpings län',
              'SE212': 'Kronobergs län',
              'SE213': 'Kalmar län',
              'SE214': 'Gotlands län',
              'SE221': 'Blekinge län',
              'SE224': 'Skåne län',
              'SE231': 'Hallands län',
              'SE232': 'Västra Götalands län',
              'SE311': 'Värmlands län',
              'SE312': 'Dalarnas län',
              'SE313': 'Gävleborgs län',
              'SE321': 'Västernorrlands län',
              'SE322': 'Jämtlands län',
              'SE331': 'Västerbottens län',
              'SE332': 'Norrbottens län',
              'SI011': 'Pomurska',
              'SI012': 'Podravska',
              'SI013': 'Koroska',
              'SI014': 'Savinjska',
              'SI015': 'Zasavska',
              'SI016': 'Spodnjeposavska',
              'SI017': 'Jugovzhodna Slovenija',
              'SI018': 'Notranjsko-kraska',
              'SI021': 'Osrednjeslovenska',
              'SI022': 'Gorenjska',
              'SI023': 'Goriska',
              'SI024': 'Obalno-kraska',
              'SK010': 'Bratislavský kraj',
              'SK021': 'Trnavský kraj',
              'SK022': 'Trenciansky kraj',
              'SK023': 'Nitriansky kraj',
              'SK031': 'Zilinský kraj',
              'SK032': 'Banskobystrický kraj',
              'SK041': 'Presovský kraj',
              'SK042': 'Kosický kraj',
              'TR100': 'Istanbul',
              'TR211': 'Tekirdag',
              'TR212': 'Edirne',
              'TR213': 'Kirklareli',
              'TR221': 'Balikesir',
              'TR222': 'Çanakkale',
              'TR310': 'Izmir',
              'TR321': 'Aydin',
              'TR322': 'Denizli',
              'TR323': 'Mugla',
              'TR331': 'Manisa',
              'TR332': 'Afyonkarahisar',
              'TR333': 'Kütahya',
              'TR334': 'Usak',
              'TR411': 'Bursa',
              'TR412': 'Eskisehir',
              'TR413': 'Bilecik',
              'TR421': 'Kocaeli',
              'TR422': 'Sakarya',
              'TR423': 'Düzce',
              'TR424': 'Bolu',
              'TR425': 'Yalova',
              'TR510': 'Ankara',
              'TR521': 'Konya',
              'TR522': 'Karaman',
              'TR611': 'Antalya',
              'TR612': 'Isparta',
              'TR613': 'Burdur',
              'TR621': 'Adana',
              'TR622': 'Mersin',
              'TR631': 'Hatay',
              'TR632': 'Kahramanmaras',
              'TR633': 'Osmaniye',
              'TR711': 'Kirikkale',
              'TR712': 'Aksaray',
              'TR713': 'Nigde',
              'TR714': 'Nevsehir',
              'TR715': 'Kirsehir',
              'TR721': 'Kayseri',
              'TR722': 'Sivas',
              'TR723': 'Yozgat',
              'TR811': 'Zonguldak',
              'TR812': 'Karabük',
              'TR813': 'Bartin',
              'TR821': 'Kastamonu',
              'TR822': 'Çankiri',
              'TR823': 'Sinop',
              'TR831': 'Samsun',
              'TR832': 'Tokat',
              'TR833': 'Çorum',
              'TR834': 'Amasya',
              'TR901': 'Trabzon',
              'TR902': 'Ordu',
              'TR903': 'Giresun',
              'TR904': 'Rize',
              'TR905': 'Artvin',
              'TR906': 'Gümüshane',
              'TRA11': 'Erzurum',
              'TRA12': 'Erzincan',
              'TRA13': 'Bayburt',
              'TRA21': 'Agri',
              'TRA22': 'Kars',
              'TRA23': 'Igdir',
              'TRA24': 'Ardahan',
              'TRB11': 'Malatya',
              'TRB12': 'Elazig',
              'TRB13': 'Bingöl',
              'TRB14': 'Tunceli',
              'TRB21': 'Van',
              'TRB22': 'Mus',
              'TRB23': 'Bitlis',
              'TRB24': 'Hakkari',
              'TRC11': 'Gaziantep',
              'TRC12': 'Adiyaman',
              'TRC13': 'Kilis',
              'TRC21': 'Sanliurfa',
              'TRC22': 'Diyarbakir',
              'TRC31': 'Mardin',
              'TRC32': 'Batman',
              'TRC33': 'Sirnak',
              'TRC34': 'Siirt',
              'UKC11': 'Hartlepool and Stockton-on-Tees',
              'UKC12': 'South Teesside',
              'UKC13': 'Darlington',
              'UKC14': 'Durham CC',
              'UKC21': 'Northumberland',
              'UKC22': 'Tyneside',
              'UKC23': 'Sunderland',
              'UKD11': 'West Cumbria',
              'UKD12': 'East Cumbria',
              'UKD31': 'Greater Manchester South',
              'UKD32': 'Greater Manchester North',
              'UKD41': 'Blackburn with Darwen',
              'UKD42': 'Blackpool',
              'UKD43': 'Lancashire CC',
              'UKD61': 'Warrington',
              'UKD62': 'Cheshire East',
              'UKD63': 'Cheshire West and Chester',
              'UKD71': 'East Merseyside',
              'UKD72': 'Liverpool',
              'UKD73': 'Sefton',
              'UKD74': 'Wirral',
              'UKE11': 'Kingston upon Hull, City of ',
              'UKE12': 'East Riding of Yorkshire',
              'UKE13': 'North and North East Lincolnshire',
              'UKE21': 'York',
              'UKE22': 'North Yorkshire CC',
              'UKE31': 'Barnsley, Doncaster and Rotherham',
              'UKE32': 'Sheffield',
              'UKE41': 'Bradford',
              'UKE42': 'Leeds',
              'UKE44': 'Calderdale and Kirklees',
              'UKE45': 'Wakefield',
              'UKF11': 'Derby',
              'UKF12': 'East Derbyshire',
              'UKF13': 'South and West Derbyshire',
              'UKF14': 'Nottingham',
              'UKF15': 'North Nottinghamshire',
              'UKF16': 'South Nottinghamshire',
              'UKF21': 'Leicester',
              'UKF22': 'Leicestershire CC and Rutland',
              'UKF24': 'West Northamptonshire',
              'UKF25': 'North Northamptonshire',
              'UKF30': 'Lincolnshire',
              'UKG11': 'Herefordshire, County of',
              'UKG12': 'Worcestershire',
              'UKG13': 'Warwickshire',
              'UKG21': 'Telford and Wrekin',
              'UKG22': 'Shropshire CC',
              'UKG23': 'Stoke-on-Trent',
              'UKG24': 'Staffordshire CC',
              'UKG31': 'Birmingham',
              'UKG32': 'Solihull',
              'UKG33': 'Coventry',
              'UKG36': 'Dudley',
              'UKG37': 'Sandwell',
              'UKG38': 'Walsall',
              'UKG39': 'Wolverhampton',
              'UKH11': 'Peterborough',
              'UKH12': 'Cambridgeshire CC',
              'UKH13': 'Norfolk',
              'UKH14': 'Suffolk',
              'UKH21': 'Luton',
              'UKH23': 'Hertfordshire',
              'UKH24': 'Bedford',
              'UKH25': 'Central Bedfordshire',
              'UKH31': 'Southend-on-Sea',
              'UKH32': 'Thurrock',
              'UKH33': 'Essex CC',
              'UKI11': 'Inner London - West',
              'UKI12': 'Inner London - East',
              'UKI21': 'Outer London - East and North East',
              'UKI22': 'Outer London - South',
              'UKI23': 'Outer London - West and North West',
              'UKJ11': 'Berkshire',
              'UKJ12': 'Milton Keynes',
              'UKJ13': 'Buckinghamshire CC',
              'UKJ14': 'Oxfordshire',
              'UKJ21': 'Brighton and Hove',
              'UKJ22': 'East Sussex CC',
              'UKJ23': 'Surrey',
              'UKJ24': 'West Sussex',
              'UKJ31': 'Portsmouth',
              'UKJ32': 'Southampton',
              'UKJ33': 'Hampshire CC',
              'UKJ34': 'Isle of Wight',
              'UKJ41': 'Medway',
              'UKJ42': 'Kent CC',
              'UKK11': 'Bristol, City of ',
              'UKK12': 'Bath and North East Somerset, North Somerset and South '
                       'Gloucestershire',
              'UKK13': 'Gloucestershire',
              'UKK14': 'Swindon',
              'UKK15': 'Wiltshire CC',
              'UKK21': 'Bournemouth and Poole',
              'UKK22': 'Dorset CC',
              'UKK23': 'Somerset',
              'UKK30': 'Cornwall and Isles of Scilly',
              'UKK41': 'Plymouth',
              'UKK42': 'Torbay',
              'UKK43': 'Devon CC',
              'UKL11': 'Isle of Anglesey',
              'UKL12': 'Gwynedd',
              'UKL13': 'Conwy and Denbighshire',
              'UKL14': 'South West Wales',
              'UKL15': 'Central Valleys',
              'UKL16': 'Gwent Valleys',
              'UKL17': 'Bridgend and Neath Port Talbot',
              'UKL18': 'Swansea',
              'UKL21': 'Monmouthshire and Newport',
              'UKL22': 'Cardiff and Vale of Glamorgan',
              'UKL23': 'Flintshire and Wrexham',
              'UKL24': 'Powys',
              'UKM21': 'Angus and Dundee City',
              'UKM22': 'Clackmannanshire and Fife',
              'UKM23': 'East Lothian and Midlothian',
              'UKM24': 'Scottish Borders',
              'UKM25': 'Edinburgh, City of',
              'UKM26': 'Falkirk',
              'UKM27': 'Perth & Kinross and Stirling',
              'UKM28': 'West Lothian',
              'UKM31': 'East Dunbartonshire, West Dunbartonshire and Helensburgh & '
                       'Lomond',
              'UKM32': 'Dumfries & Galloway',
              'UKM33': 'East Ayrshire and North Ayrshire mainland',
              'UKM34': 'Glasgow City',
              'UKM35': 'Inverclyde, East Renfrewshire and Renfrewshire',
              'UKM36': 'North Lanarkshire',
              'UKM37': 'South Ayrshire',
              'UKM38': 'South Lanarkshire',
              'UKM50': 'Aberdeen City and Aberdeenshire',
              'UKM61': 'Caithness & Sutherland and Ross & Cromarty',
              'UKM62': 'Inverness & Nairn and Moray, Badenoch & Strathspey',
              'UKM63': 'Lochaber, Skye & Lochalsh, Arran & Cumbrae and Argyll & Bute',
              'UKM64': 'Eilean Siar (Western Isles)',
              'UKM65': 'Orkney Islands',
              'UKM66': 'Shetland Islands',
              'UKN01': 'Belfast',
              'UKN02': 'Outer Belfast',
              'UKN03': 'East of Northern Ireland (UK)',
              'UKN04': 'North of Northern Ireland (UK)',
              'UKN05': 'West and South of Northern Ireland (UK)'}
